# nonk8s
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: v-rising-server
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: ghcr.io/hermesdj/v-rising-server
      context: .
      docker: {}
deploy:
  kubectl:
    defaultNamespace: v-rising
    remoteManifests:
      - k8s/rbac.yaml
      - k8s/api-env.yaml
      - k8s/api-deployment.yaml
      - k8s/api-service.yaml
      - k8s/api-ingressroute.yaml
profiles:
  - name: prod
    activation:
      - kubeContext: preprod
    deploy:
      kubeContext: preprod
      kubectl:
        defaultNamespace: v-rising
        remoteManifests:
          - k8s/rbac.yaml
          - k8s/api-env.yaml
          - k8s/api-deployment.yaml
          - k8s/api-service.yaml
          - k8s/api-ingressroute.yaml
