# nonk8s
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: v-rising-server
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: ghcr.io/hermesdj/v-rising-server
      context: .
      docker: {}
manifests:
  rawYaml:
    - k8s/service-account.yaml
    - k8s/role.yaml
    - k8s/role-binding.yaml
    - k8s/api-server-config.yaml
    - k8s/api-env.yaml
    - k8s/api-deployment.yaml
    - k8s/api-service.yaml
    - k8s/api-ingressroute.yaml
deploy:
  kubectl:
    defaultNamespace: v-rising
profiles:
  - name: prod
    activation:
      - kubeContext: preprod
    deploy:
      kubeContext: preprod
      kubectl:
        defaultNamespace: v-rising
