apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: v-rising-game-ingressroute
  namespace: v-rising
spec:
  entryPoints:
    - gameport
  routes:
    - services:
        - name: v-rising-api-service
          port: 9876
