apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v-rising-server-backup-pvc
  namespace: v-rising
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: glusterfs-reclaim
  volumeName: v-rising-backup-pv
  resources:
    requests:
      storage: 500Mi
