apiVersion: v1
kind: ServiceAccount
metadata:
  name: v-rising-api-reader
  namespace: v-rising
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-v-rising-api-reader
  namespace: v-rising
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-v-rising-api-reader
  namespace: v-rising
subjects:
  - kind: ServiceAccount
    name: v-rising-api-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-v-rising-api-reader
