apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-v-rising-api-reader
  namespace: v-rising
subjects:
  - kind: ServiceAccount
    name: v-rising-api-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-v-rising-api-reader
