i18n:
  defaultLocale: fr
api:
  port: 8080
  auth:
    returnURL: http://localhost:8080/api/auth/steam/return
    realm: http://localhost:8080/
  session:
    params:
      resave: false
      saveUninitialized: false
      name: v-rising-session.sid
server:
  runOnStartup: true
  tz: Europe/Paris
  exeFileName: VRisingServer.exe
  serverPath: Z:\SteamLibrary\steamapps\common\VRising\VRising_Server
  dataPath: ./server-data
  backupPath: ./server-data/Backups
  compressBackupSaves: true
  backupCount: 5
  name: V Rising Test Server
  saveName: world1
  logFile: ./logs/server.log
  gamePort: 9876
  queryPort: 9877
  defaultAdminList:
    - '76561198005048084'
  defaultBanList: [ ]
  api:
    enabled: true
    bindAddress: \*
    bindPort: 9090
    basePath: /
    accessList:
    prometheusDelay: 30
    metrics:
      retain: 1
  mods:
    thunderstore:
      url: https://v-rising.thunderstore.io/api/v1
    bepinex:
      url: https://github.com/decaprime/VRising-Modding/releases/download/1.668.2/BepInEx_V_Rising_Experimental_Dev_1.668.2.zip

log:
  level: debug
rcon:
  enabled: true
  host: 127.0.0.1
  port: 25575
steam:
  query:
    enabled: true
    pollingDelay: 30000
    timeout: 2000
    attempts: 5
